language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install: true

branches:
  only:
    - master

script: mvn clean test jacoco:report && mvn clean install -DskipTests -Dgpg.skip=true && mvn -f real-roaring-dataset/pom.xml clean install && mvn -f ./jmh/pom.xml test

after_success:
  - mvn coveralls:report
