language: java
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install: true

branches:
  only:
    - master

script:
 - mvn clean test jacoco:report install -Dgpg.skip=true
 - mvn -f real-roaring-dataset/pom.xml clean install
# Repeatedly fails for no discernable reason:
# - mvn -f ./jmh/pom.xml test -DBITMAP_TYPES=ROARING_ONLY

after_success:
  - mvn coveralls:report
